apiVersion: v1
kind: Service

metadata:
  name: swiggy-svc
  namespace: swiggy-ns

spec:
  selector:
    app: swiggy

  ports:
    - protocol: TCP
      port: 3000              # cluster / host port
      targetPort : 3000       # container port

